# Generated by Django 6.0.4 on 2026-05-02 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. 18mm diameter, 45cm chain', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='hallmark',
            field=models.CharField(blank=True, help_text='e.g. 925, 750, Pt950', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='Can be engraved or resized on request'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='metal',
            field=models.CharField(blank=True, choices=[('gold_18k', '18K Gold'), ('gold_14k', '14K Gold'), ('gold_9k', '9K Gold'), ('rose_gold', 'Rose Gold'), ('white_gold', 'White Gold'), ('silver_925', 'Sterling Silver (925)'), ('platinum', 'Platinum'), ('titanium', 'Titanium'), ('stainless', 'Stainless Steel'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes_available',
            field=models.CharField(blank=True, help_text='Comma-separated sizes, e.g. 5,6,7,8', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stone',
            field=models.CharField(blank=True, choices=[('', 'No Stone'), ('diamond', 'Diamond'), ('ruby', 'Ruby'), ('emerald', 'Emerald'), ('sapphire', 'Sapphire'), ('pearl', 'Pearl'), ('amethyst', 'Amethyst'), ('opal', 'Opal'), ('topaz', 'Topaz'), ('garnet', 'Garnet'), ('turquoise', 'Turquoise'), ('morganite', 'Morganite'), ('cubic_zirconia', 'Cubic Zirconia'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='stone_carat',
            field=models.CharField(blank=True, help_text='e.g. 0.5ct, 1ct total weight', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Item weight in grams', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(max_length=250)),
                ('address_line2', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('gift_note', models.TextField(blank=True, help_text='Optional gift message')),
                ('payment_method', models.CharField(choices=[('stripe', 'Credit / Debit Card (Stripe)'), ('paypal', 'PayPal'), ('cod', 'Cash on Delivery'), ('bank', 'Bank Transfer')], max_length=20)),
                ('payment_id', models.CharField(blank=True, help_text='Stripe/PayPal transaction ID', max_length=300)),
                ('is_paid', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'unique_together': {('cart', 'product', 'size')},
            },
        ),
    ]
